package meditrack.logic.commands;

import java.util.Objects;

/**
 * Represents the immutable outcome of a successfully executed command.
 * Contains the feedback message that will be routed back to the UI for the user to read.
 */
public class CommandResult {

    private final String feedbackToUser;

    /**
     * Constructs a CommandResult with the specified feedback message.
     *
     * @param feedbackToUser The message to display to the user. Must not be null.
     */
    public CommandResult(String feedbackToUser) {
        this.feedbackToUser = Objects.requireNonNull(feedbackToUser, "Feedback message must not be null.");
    }

    /**
     * Retrieves the feedback message generated by the command.
     *
     * @return The feedback string.
     */
    public String getFeedbackToUser() {
        return feedbackToUser;
    }

    /**
     * Checks equality based on the feedback string.
     */
    @Override
    public boolean equals(Object other) {
        if (other == this) {
            return true;
        }
        if (!(other instanceof CommandResult)) {
            return false;
        }
        return feedbackToUser.equals(((CommandResult) other).feedbackToUser);
    }

    @Override
    public int hashCode() {
        return Objects.hash(feedbackToUser);
    }
}